from model.destination import *
from model.employee import *
from model.flight_attendant import *
from model.flight_manager import *
from model.flight import *
from model.manager import *
from model.pilot import *
from model.plane import *
from model.voyage import *
